### ISSUE TITLE
Documentation when running tests

### ISSUE THREAD

**Issue by joseluistorres** [alejandrodevs/mass_insert#4]
Hi @alejandrogutierrez I'm sure you are aware of this, perhaps you should include in the README how to run migrations first in order to run tests
```
bundle exec rake db:create RAILS_ENV=mysql2
bundle exec rake db:create RAILS_ENV=postgresql
bundle exec rake db:migrate RAILS_ENV=mysql2
bundle exec rake db:migrate RAILS_ENV=postgresql
```
And update username and password in database.yml I hope this helps!

Cheers

**Comment by alejandrodevs** [comment]
This has been solved. 👍
